<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-100463316-3', 'auto');
  ga('send', 'pageview');

</script>

\cr

## Interests 

I'm fond of __Data Science__ and an __R(cpp)__ enthusiast. I'm co-organizer of [the Grenoble R user group](https://r-in-grenoble.github.io/).

## Current work

I am a PhD student (2016 - 2019) in predictive human genetics in [BCM team](http://www-timc.imag.fr/rubrique44.html), Laboratoire TIMC-IMAG, Grenoble, France. My supervisors are [Michael Blum](https://twitter.com/mblum_g) (TIMC-IMAG) and [Hugues Aschard](https://research.pasteur.fr/fr/member/hugues-aschard/) (Institut Pasteur). My thesis is funded by the [LabEx PERSYVAL-Lab](https://persyval-lab.org/en).

I am currently working on a comparison of methods for predicting disease based on massive SNP arrays.

I am also trying to contribute to R 

- by submitting my own packages to CRAN (or just [GitHub](https://github.com/privefl?tab=repositories)),
- by [contributing to other projects when I can](https://github.com/pulls?utf8=%E2%9C%93&q=author%3Aprivefl+),
- by asking and answering questions on [Stack Overflow](http://stackoverflow.com/users/6103040/f-privé),
- by posting on [R-bloggers](https://www.r-bloggers.com/).

## Hometown -- Education

I'm from [Troyes](https://en.wikipedia.org/wiki/Troyes), France. 
I naturally like Champagne.

I was in prep school in [Dijon](https://en.wikipedia.org/wiki/Dijon).

Then, I graduated from [ENSIMAG](https://goo.gl/2aDwm1), an engineer school in __Informatics__ and __Applied Mathematics__ in [Grenoble](https://en.wikipedia.org/wiki/Grenoble). 

I did both my internships in Research, 

- the former on goodness-of-fit tests for the Weibull distribution with censored data (through Monte Carlo simulations),
- the latter in predictive human genetics, studying a massive dataset on [Celiac disease](https://en.wikipedia.org/wiki/Coeliac_disease).


## Publications

- Efficient management and analysis of large-scale genome-wide data with two R packages: bigstatsr and bigsnpr. [[Preprint]](http://www.biorxiv.org/content/early/2017/09/19/190926)

## Conferences

- [hackseq 2017](http://www.hackseq.com/): Developing advanced R tutorials for genomic data analysis [[Website]](https://hackseq.github.io/2017_project_5/)

- [useR!2017](https://user2017.brussels/): The R package **bigstatsr**:
Memory- and Computation-Efficient Tools for Big Matrices. [[Recording]](https://t.co/aYt0q8MeXJ)

- [ALT'2016](http://alt2016.sciencesconf.org/): Goodness-of-fit tests for the Weibull distribution with censored data. [[Slides]](slides_GOFW.pdf#1)

### Some other presentations

- [Visualisation with ggplot2](https://privefl.github.io/R-presentation/ggplot2.html) ([Grenoble RUG](https://r-in-grenoble.github.io/))

- [Thesis follow-up n°1](https://privefl.github.io/thesis-docs/suivi-these.html)

- [Getting My Colleagues Hooked on R](https://privefl.github.io/R-presentation/pResentation.html) ([Team seminars](http://membres-timc.imag.fr/Nicolas.Thierry-Mieg/jc_bcm.html))