---
title: "Première compétence: Développer un réseau à l’international"
---

Le but est de développer un réseau à l’international. Cela a beaucoup d’avantages d’avoir un large réseau à l’international, mais je ne détaillerai pas ce point. Je veux développer un réseau à l’international dans deux communautés différentes, celle du langage R (en priorité) et celle de l’analyse de données génétiques (mon sujet de thèse). Pour cela, j’essaie de devenir de plus en plus visible sur la scène internationale. 

D’abord, juste avant le début de ma thèse, j’ai d’abord créé mon site internet et mon blog sur R. J’essaie de bloguer assez régulièrement à propos de R et mon blog est relayé sur [R-bloggers](https://www.r-bloggers.com/), une plateforme qui regroupe 750 R bloggers et lue par des milliers de personnes à l’international. J’ai récemment décidé de suivre le flux de personnes sur mon blog en utilisant Google Analytics. 

J’essaie également de créer des packages R et de contribuer à ceux des autres via GitHub. GitHub est un bon moyen de rendre son travail visible à l’international et de faciliter les collaborations. 

J’essaie également d’être présent sur Twitter, qui est largement utilisé par les deux communautés qui m’intéressent. Je commence à avoir des followers, alors même que je n’ai pas encore publié de papier scientifique ou de package R “officiel”. Je compte bientôt remédier à cela en allant présenter un de mes packages à la communauté R lors d’une conférence internationale regroupant 1000 personnes (http://sched.co/Axrw). Ce aussi sera l’occasion de faire des rencontres et d’établir des contacts. 

Enfin, en plus de prendre part dans une communauté internationale, je pense que c’est aussi très important de prendre part dans une communauté plus locale. C’est pour cela que j’ai lancé l’initiative de faire une communauté R à Grenoble, qui commencera à être active en Septembre 2017 (https://r-in-grenoble.github.io/).

Ainsi, mon réseau à l’international est en cours de développement. On peut considérer que c’est un processus qui prend du temps, mais que les indicateurs montrent que je suis sur la bonne voie.
